import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, BriefcaseBusiness, Check, Edit3, Filter, ImagePlus, Laptop, Menu, Minus, Package, Palette, Plus, Search, ShoppingBag, ShoppingCart, Sparkles, Trash2, Upload, X, ZoomIn, ZoomOut } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type ChangeEvent, type PointerEvent } from "react";
import { supabase, ADMIN_EMAIL, IMAGE_BUCKET } from "@/integrations/supabase/client";

export const Route = createFileRoute("/")({ component: Index });
type Category = "Papelaria" | "Informática";
type Product = { id:string; name:string; category:Category; description:string; price:number; code:string; stock:number; available:boolean; image?:string };
type CartItem = { productId:string; quantity:number };
type Crop = { image:string; x:number; y:number; zoom:number };
const ORDER_CONTACT = "";
const money=(n:number)=>new Intl.NumberFormat("pt-MZ",{style:"currency",currency:"MZN",maximumFractionDigits:2}).format(n);
const defaultServices=[{title:"Criação de logótipos",description:"Marcas memoráveis e profissionais.",type:"logo"},{title:"Identidade visual",description:"Sistemas visuais consistentes para a sua marca.",type:"identity"},{title:"Cartões de visita",description:"Apresentação profissional para o seu negócio.",type:"card"},{title:"Flyers e cartazes",description:"Comunicação clara, impactante e pronta para impressão.",type:"flyer"},{title:"Convites",description:"Peças personalizadas para eventos e celebrações.",type:"invite"},{title:"Banners para redes sociais",description:"Conteúdo visual alinhado à sua identidade.",type:"social"},{title:"Menus",description:"Menus elegantes e preparados para impressão.",type:"menu"},{title:"Material promocional",description:"Peças gráficas para campanhas e produtos.",type:"promo"},{title:"Impressão e personalização",description:"Do design ao material físico.",type:"print"},{title:"Soluções criativas",description:"Projetos sob medida para empresas e eventos.",type:"creative"}];
const portfolio=[["Identidade de marca","Branding","brand"],["Campanha promocional","Publicidade","promo"],["Menu profissional","Menus","menu"],["Comunicação digital","Redes sociais","social"],["Material corporativo","Corporativo","corp"],["Design para eventos","Eventos","event"]];
const starterProducts:Product[]=[];

function Index(){
 const [mobile,setMobile]=useState(false),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<CartItem[]>([]),[services,setServices]=useState<any[]>([]),[q,setQ]=useState(""),[cat,setCat]=useState<"Todos"|Category>("Todos"),[panel,setPanel]=useState<"product"|"cart"|"checkout"|"admin"|null>(null),[editing,setEditing]=useState<Product|null>(null),[light,setLight]=useState<any>(null),[toast,setToast]=useState(""),[scroll,setScroll]=useState(0),[isAdmin,setIsAdmin]=useState(false);
 useEffect(()=>{let active=true;const loadRemote=async()=>{const [{data:ps,error:pe},{data:ss,error:se}]=await Promise.all([supabase.from("products").select("*").order("created_at",{ascending:false}),supabase.from("services").select("*").order("created_at",{ascending:true})]);if(!active)return;if(pe||se){console.error(pe||se);setToast("Não foi possível carregar o catálogo online.")}else{setProducts((ps??[]) as Product[]);setServices((ss??[]) as any[])} };loadRemote();const check=async()=>{const {data:{user}}=await supabase.auth.getUser();setIsAdmin(user?.email?.toLowerCase()===ADMIN_EMAIL)};check();const {data}=supabase.auth.onAuthStateChange((_event,session)=>setIsAdmin(session?.user?.email?.toLowerCase()===ADMIN_EMAIL));return()=>{active=false;data.subscription.unsubscribe()};},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)},[toast]);
 const filtered=useMemo(()=>products.filter(p=>(cat==="Todos"||p.category===cat)&&[p.name,p.code,p.description].join(" ").toLowerCase().includes(q.toLowerCase())),[products,q,cat]);
 const details=cart.map(i=>{const p=products.find(x=>x.id===i.productId);return p?{...i,product:p,subtotal:p.price*i.quantity}:null}).filter(Boolean) as Array<CartItem&{product:Product;subtotal:number}>;
 const count=cart.reduce((s,i)=>s+i.quantity,0),total=details.reduce((s,i)=>s+i.subtotal,0);
 const open=(p?:Product)=>{setScroll(window.scrollY);setEditing(p??null);setPanel("product")};
 const close=()=>{const y=scroll;setPanel(null);setEditing(null);requestAnimationFrame(()=>window.scrollTo({top:y,behavior:"auto"}))};
 const add=(p:Product)=>{if(!p.available||p.stock<1)return;setCart(c=>{const x=c.find(i=>i.productId===p.id);return x?c.map(i=>i.productId===p.id?{...i,quantity:Math.min(p.stock,i.quantity+1)}:i):[...c,{productId:p.id,quantity:1}]});setToast("Produto adicionado ao carrinho.")};
 const qty=(id:string,d:number)=>setCart(c=>c.map(i=>{if(i.productId!==id)return i;const p=products.find(x=>x.id===id);return {...i,quantity:Math.min(p?.stock??999,i.quantity+d)}}).filter(i=>i.quantity>0));
 const nav=[["Início","inicio"],["Design Gráfico","design"],["Serviços","servicos"],["Portfólio","portfolio"],["Loja","loja"],["Contactos","contactos"]];
 return <div className="parrot-site">
 <header className="site-header"><a href="#inicio" className="brand" onClick={()=>setMobile(false)}><span className="brand-p">P</span><span><b>PARROT</b><small>Design Gráfico & Soluções Criativas</small></span></a><button className="mobile-menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><nav className={mobile?"main-nav open":"main-nav"}>{nav.map(([n,id])=><a key={id} href={"#"+id} onClick={()=>setMobile(false)}>{n}</a>)}<button className="nav-cart" onClick={()=>{setScroll(window.scrollY);setPanel("cart")}}><ShoppingCart/> Carrinho {count>0&&<span>{count}</span>}</button></nav></header>
 <main>
 <section id="inicio" className="hero"><div className="hero-copy"><span className="eyebrow">DESIGN GRÁFICO • IMPRESSÃO • SOLUÇÕES CRIATIVAS</span><h1>Ideias que ganham <em>forma</em>. Marcas que ganham valor.</h1><p>Transformamos ideias em comunicação visual profissional para empresas, empreendedores e eventos.</p><div className="hero-buttons"><a className="btn primary" href="#servicos">Ver serviços <ArrowRight/></a><a className="btn ghost" href="#portfolio">Ver portfólio</a><a className="btn light" href="#loja">Visitar loja</a></div><div className="proof"><span><Check/> Criatividade</span><span><Check/> Qualidade</span><span><Check/> Compromisso</span></div></div><div className="hero-art"><div className="art back"><span>BRAND</span><b>YOUR<br/>STORY</b></div><div className="art front"><i>P</i><span>PARROT</span><b>CREATE<br/>WITH PURPOSE</b></div></div></section>
 <section id="design" className="intro"><div><span className="kicker">DESIGN GRÁFICO</span><h2>A criatividade é o nosso ponto de partida.</h2></div><p>Do conceito à peça final, cuidamos da comunicação visual para que a sua marca seja reconhecida, lembrada e valorizada.</p></section>
 <section id="servicos" className="section"><Head kicker="O QUE FAZEMOS" title="Serviços para dar força à sua comunicação" text="Escolha o que precisa ou fale connosco para encontrarmos a melhor solução."/><div className="service-grid">{services.map(s=><ServiceCard key={s.type} {...s} isAdmin={isAdmin} onImageChange={async image=>{const url=await uploadImage(image,"services");const {error}=await supabase.from("services").update({image:url,updated_at:new Date().toISOString()}).eq("type",s.type);if(error)throw error;setServices(xs=>xs.map(x=>x.type===s.type?{...x,image:url}:x))}} onEdit={async(title,description)=>{const {error}=await supabase.from("services").update({title,description,updated_at:new Date().toISOString()}).eq("type",s.type);if(error)throw error;setServices(xs=>xs.map(x=>x.type===s.type?{...x,title,description}:x))}}/>)}</div>{isAdmin&&<div className="section-add"><button className="btn primary" onClick={async()=>{const type="custom-"+crypto.randomUUID();const service={type,title:"Novo serviço",description:"Descreva este serviço da Parrot.",image:null};const {error}=await supabase.from("services").insert(service);if(error){setToast("Não foi possível adicionar o serviço.");return}setServices(xs=>[...xs,service]);setToast("Novo serviço adicionado.")}}><Plus/> Adicionar serviço</button></div>}</section>
 <section id="portfolio" className="section portfolio"><Head kicker="PORTFÓLIO" title="Trabalho pensado para destacar marcas" text="Uma seleção visual para apresentar a abordagem criativa da Parrot."/><div className="portfolio-grid">{portfolio.map(([t,c,tone])=><button className={"portfolio-card "+tone} key={t} onClick={()=>setLight({t,c,tone})}><div><span>PARROT</span><b>{t}</b><small>{c}</small></div><footer><b>{t}</b><span>{c}</span></footer></button>)}</div></section>
 <section id="loja" className="shop"><div className="shop-top"><div><span className="kicker">LOJA PARROT</span><h2>Papelaria e informática, num só lugar.</h2><p>Materiais para o dia a dia do seu negócio, com pedidos simples.</p></div><div className="shop-actions">{isAdmin&&<button className="btn primary" onClick={()=>open()}><Plus/> Adicionar produto</button>}<button className="btn outline" onClick={()=>{setScroll(window.scrollY);setPanel("cart")}}><ShoppingCart/> Carrinho {count>0&&"("+count+")"}</button></div></div>
 <div className="toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar produto..."/></label><div className="filters"><Filter/>{(["Todos","Papelaria","Informática"] as const).map(x=><button key={x} className={cat===x?"active":""} onClick={()=>setCat(x)}>{x}</button>)}</div></div>
 {products.length===0?<div className="empty"><ShoppingBag/><h3>A loja ainda não tem produtos disponíveis.</h3><p>Adicione o primeiro produto para começar a montar o catálogo.</p><button className="btn primary" onClick={()=>open()}><Plus/> Adicionar produto</button></div>:filtered.length===0?<div className="empty"><Search/><h3>Nenhum produto encontrado.</h3><p>Tente outro nome ou categoria.</p></div>:<div className="products">{filtered.map(p=><ProductCard key={p.id} p={p} onAdd={add} onEdit={()=>open(p)} isAdmin={isAdmin}/>)}</div>}</section>
 <section id="contactos" className="contact"><div><span className="kicker">CONTACTOS</span><h2>Vamos transformar a sua ideia em algo real.</h2><p>Fale com a Parrot para pedir orçamento, esclarecer dúvidas ou apresentar o seu próximo projeto.</p></div><div className="contact-box"><b>PARROT</b><span>Design Gráfico & Soluções Criativas</span><p>Atendimento em Vilankulo, Inhambane e todo Moçambique.</p><a href="#inicio" className="btn light">Voltar ao início <ArrowRight/></a></div></section>
 </main><footer className="site-footer"><span>© {new Date().getFullYear()} Parrot Design Gráfico e Soluções Criativas.</span><span>Criatividade • Qualidade • Compromisso</span><button className="admin-link" onClick={()=>{setScroll(window.scrollY);setPanel("admin")}}>{isAdmin?"Painel administrativo":"Área administrativa"}</button></footer>
 {panel==="product"&&<ProductPanel product={editing} onClose={close} onSave={async p=>{try{const image=p.image?.startsWith("data:")?await uploadImage(p.image,"products"):p.image;const remote={...p,image:image??null,updated_at:new Date().toISOString()};const {data,error}=await supabase.from("products").upsert(remote).select().single();if(error)throw error;setProducts(c=>editing?c.map(x=>x.id===p.id?(data as Product):x):[data as Product,...c]);setPanel(null);setEditing(null);setToast(editing?"Produto atualizado.":"Produto adicionado.");requestAnimationFrame(()=>window.scrollTo({top:scroll,behavior:"auto"}))}catch(e){console.error(e);setToast("Não foi possível guardar o produto.")}}} onDelete={editing?async()=>{const {error}=await supabase.from("products").delete().eq("id",editing.id);if(error){setToast("Não foi possível excluir o produto.");return}setProducts(c=>c.filter(x=>x.id!==editing.id));setCart(c=>c.filter(x=>x.productId!==editing.id));close()}:undefined}/>}
 {panel==="cart"&&<CartPanel items={details} total={total} onClose={close} onQty={qty} onRemove={id=>setCart(c=>c.filter(x=>x.productId!==id))} onCheckout={()=>setPanel("checkout")}/>}
 {panel==="checkout"&&<Checkout items={details} total={total} onClose={close} onSend={(name,phone,notes)=>{if(!ORDER_CONTACT){setToast("O contacto de pedidos ainda não está configurado no site.");return}const body="Pedido Parrot%0ACliente: "+name+"%0ATelefone: "+phone+"%0AObservações: "+notes+"%0A%0A"+details.map(i=>i.product.name+" x"+i.quantity+" — "+money(i.subtotal)).join("%0A")+"%0ATotal: "+money(total);window.open("https://wa.me/"+ORDER_CONTACT+"?text="+body,"_blank");setCart([]);setPanel(null);setToast("Pedido preparado para envio.")}}/>}
 {panel==="admin"&&<AdminPanel isAdmin={isAdmin} onClose={close} onLogin={ok=>{setIsAdmin(ok);setPanel(null);setToast(ok?"Acesso administrativo autorizado.":"Sessão terminada.")}}/>}{light&&<div className="lightbox" onClick={()=>setLight(null)}><button onClick={()=>setLight(null)}><X/></button><div className={"light-art "+light.tone} onClick={e=>e.stopPropagation()}><span>PARROT</span><b>{light.t}</b><small>{light.c}</small></div></div>}{toast&&<div className="toast"><Check/> {toast}</div>}
 </div>
}
function ServiceCard({title,description,type,image,isAdmin,onImageChange,onEdit}:{title:string;description:string;type:string;image?:string;isAdmin:boolean;onImageChange:(image:string)=>Promise<void>;onEdit:(title:string,description:string)=>Promise<void>}){const [crop,setCrop]=useState<Crop|null>(null);const [editing,setEditing]=useState(false);const [t,setT]=useState(title);const [d,setD]=useState(description);const ref=useRef<HTMLInputElement>(null);const choose=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith("image/"))return;const r=new FileReader();r.onload=()=>setCrop({image:String(r.result),x:0,y:0,zoom:1});r.readAsDataURL(f);e.target.value=""};return <><article className="service"><div className="service-illustration">{image?<img src={image} alt={title}/>:<div className="service-image-empty"><ImagePlus/><span>Adicione uma imagem real do serviço</span></div>}<button className="service-image-btn" type="button" onClick={()=>ref.current?.click()}><Edit3/> {image?"Alterar imagem":"Adicionar imagem"}</button><input ref={ref} hidden type="file" accept="image/*" onChange={choose}/></div>{editing?<div className="service-edit"><input value={t} onChange={e=>setT(e.target.value)} placeholder="Nome do serviço"/><textarea rows={2} value={d} onChange={e=>setD(e.target.value)} placeholder="Descrição"/><div><button className="btn ghost small" onClick={()=>{setT(title);setD(description);setEditing(false)}}>Cancelar</button><button className="btn primary small" onClick={()=>{onEdit(t.trim()||title,d.trim()||description);setEditing(false)}}><Check/> Guardar</button></div></div>:<><h3>{title}</h3><p>{description}</p><div className="service-links"><a href="#contactos">Pedir orçamento <ArrowRight/></a>{isAdmin&&<button type="button" className="service-edit-btn" onClick={()=>setEditing(true)}><Edit3/> Editar</button>}</div></>}</article>{crop&&<CropEditor crop={crop} onCancel={()=>setCrop(null)} onApply={async next=>{try{await onImageChange(next);setCrop(null)}catch(e){console.error(e)}}}/>}</>}

function Head({kicker,title,text}:{kicker:string;title:string;text:string}){return <div className="section-head"><div><span className="kicker">{kicker}</span><h2>{title}</h2></div><p>{text}</p></div>}
function ProductCard({p,onAdd,onEdit,isAdmin}:{p:Product;onAdd:(p:Product)=>void;onEdit:()=>void;isAdmin:boolean}){return <article className="product-card"><div className="product-img">{p.image?<img src={p.image} alt={p.name}/>:<div className="no-image"><Package/><span>Sem fotografia</span></div>}<span className={p.available&&p.stock>0?"stock in":"stock"}>{p.available&&p.stock>0?p.stock+" em stock":"Indisponível"}</span></div><div className="product-info"><small>{p.category}</small><h3>{p.name}</h3><p>{p.description}</p><div className="product-meta"><span>Código: {p.code||"—"}</span><b>{money(p.price)}</b></div><div className="product-actions"><button className="btn primary small" disabled={!p.available||p.stock<1} onClick={()=>onAdd(p)}><ShoppingCart/> Adicionar</button>{isAdmin&&<button className="icon-btn" onClick={onEdit} title="Editar produto"><Edit3/></button>}</div></div></article>}
function ProductPanel({product,onClose,onSave,onDelete}:{product:Product|null;onClose:()=>void;onSave:(p:Product)=>Promise<void>;onDelete?:()=>void}){const [d,setD]=useState<Product>(product??{id:crypto.randomUUID(),name:"",category:"Papelaria",description:"",price:0,code:"",stock:0,available:true});const [crop,setCrop]=useState<Crop|null>(null);const ref=useRef<HTMLInputElement>(null);const choose=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith("image/"))return;const r=new FileReader();r.onload=()=>setCrop({image:String(r.result),x:0,y:0,zoom:1});r.readAsDataURL(f);e.target.value=""};return <><div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}/><aside className="panel"><div className="panel-head"><div><span className="kicker">{product?"CATÁLOGO":"NOVO PRODUTO"}</span><h2>{product?"Editar produto":"Adicionar produto"}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="panel-body"><label>Nome do produto<input value={d.name} onChange={e=>setD({...d,name:e.target.value})} placeholder="Ex.: Resma A4 80g"/></label><div className="form-row"><label>Categoria<select value={d.category} onChange={e=>setD({...d,category:e.target.value as Category})}><option>Papelaria</option><option>Informática</option></select></label><label>Código<input value={d.code} onChange={e=>setD({...d,code:e.target.value})} placeholder="PRT-001"/></label></div><label>Descrição<textarea rows={3} value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></label><div className="form-row"><label>Preço (MZN)<input type="number" min="0" value={d.price} onChange={e=>setD({...d,price:Number(e.target.value)})}/></label><label>Quantidade em stock<input type="number" min="0" value={d.stock} onChange={e=>setD({...d,stock:Math.max(0,Number(e.target.value))})}/></label></div><label className="toggle"><span><b>Disponível</b><small>Permitir encomendas deste produto.</small></span><input type="checkbox" checked={d.available} onChange={e=>setD({...d,available:e.target.checked})}/></label><div className="upload"><div>{d.image?<img src={d.image} alt=""/>:<ImagePlus/>}</div><span><b>Fotografia do produto</b><small>Escolha uma imagem para abrir o recorte manual 4:3.</small><button className="btn outline small" onClick={()=>ref.current?.click()}><Upload/> {d.image?"Substituir fotografia":"Escolher fotografia"}</button><input ref={ref} hidden type="file" accept="image/*" onChange={choose}/></span></div></div><div className="panel-foot">{onDelete&&<button className="danger" onClick={onDelete}><Trash2/> Excluir</button>}<div><button className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" disabled={!d.name.trim()} onClick={()=>void onSave(d)}><Check/> Guardar produto</button></div></div></aside>{crop&&<CropEditor crop={crop} onCancel={()=>setCrop(null)} onApply={image=>{setD(x=>({...x,image}));setCrop(null)}}/>}</>}
function CropEditor({crop,onCancel,onApply}:{crop:Crop;onCancel:()=>void;onApply:(image:string)=>void}){const [s,setS]=useState(crop);const drag=useRef<{x:number;y:number;sx:number;sy:number}|null>(null);const down=(e:PointerEvent<HTMLDivElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:s.x,y:s.y,sx:e.clientX,sy:e.clientY}};const move=(e:PointerEvent<HTMLDivElement>)=>{if(!drag.current)return;setS(x=>({...x,x:drag.current!.x+e.clientX-drag.current!.sx,y:drag.current!.y+e.clientY-drag.current!.sy}))};const apply=()=>{const c=document.createElement("canvas");c.width=1200;c.height=900;const ctx=c.getContext("2d"),img=new Image();img.onload=()=>{const scale=Math.max(c.width/img.width,c.height/img.height)*s.zoom,w=img.width*scale,h=img.height*scale;ctx?.drawImage(img,(c.width-w)/2+s.x*2.5,(c.height-h)/2+s.y*2.5,w,h);onApply(c.toDataURL("image/jpeg",.9))};img.src=s.image};return <div className="crop-overlay"><div className="crop-panel"><div className="panel-head"><div><span className="kicker">EDITOR DE IMAGEM</span><h2>Recortar fotografia</h2></div><button className="icon-btn" onClick={onCancel}><X/></button></div><p>Arraste a imagem e ajuste o zoom. O enquadramento final será guardado em 4:3.</p><div className="crop-stage" onPointerDown={down} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><img src={s.image} alt="" style={{transform:"translate(calc(-50% + "+s.x+"px), calc(-50% + "+s.y+"px)) scale("+s.zoom+")"}}/><div className="crop-frame"/></div><div className="zoom"><button className="icon-btn" onClick={()=>setS(x=>({...x,zoom:Math.max(.5,x.zoom-.1)}))}><ZoomOut/></button><input type="range" min=".5" max="3" step=".05" value={s.zoom} onChange={e=>setS(x=>({...x,zoom:Number(e.target.value)}))}/><button className="icon-btn" onClick={()=>setS(x=>({...x,zoom:Math.min(3,x.zoom+.1)}))}><ZoomIn/></button><b>{Math.round(s.zoom*100)}%</b></div><div className="crop-foot"><button className="btn ghost" onClick={onCancel}>Cancelar</button><button className="btn primary" onClick={apply}><Check/> Aplicar recorte</button></div></div></div>}
function CartPanel({items,total,onClose,onQty,onRemove,onCheckout}:{items:any[];total:number;onClose:()=>void;onQty:(id:string,d:number)=>void;onRemove:(id:string)=>void;onCheckout:()=>void}){return <><div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}/><aside className="panel cart-panel"><div className="panel-head"><div><span className="kicker">LOJA</span><h2>Seu carrinho</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="panel-body">{items.length===0?<div className="empty-cart"><ShoppingCart/><h3>O carrinho está vazio.</h3><p>Adicione produtos da loja para continuar.</p></div>:items.map(i=><div className="cart-item" key={i.product.id}><div className="cart-thumb">{i.product.image?<img src={i.product.image} alt=""/>:<Package/>}</div><div><b>{i.product.name}</b><small>{money(i.product.price)}</small><div className="quantity"><button onClick={()=>onQty(i.product.id,-1)}><Minus/></button><span>{i.quantity}</span><button onClick={()=>onQty(i.product.id,1)}><Plus/></button></div></div><div className="cart-side"><b>{money(i.subtotal)}</b><button onClick={()=>onRemove(i.product.id)}><Trash2/></button></div></div>)}</div>{items.length>0&&<div className="panel-foot total"><div><span>Total</span><b>{money(total)}</b></div><button className="btn primary" onClick={onCheckout}>Continuar para pedido <ArrowRight/></button></div>}</aside></>}
function Checkout({items,total,onClose,onSend}:{items:any[];total:number;onClose:()=>void;onSend:(a:string,b:string,c:string)=>void}){const[n,setN]=useState(""),[p,setP]=useState(""),[o,setO]=useState("");return <><div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}/><aside className="panel"><div className="panel-head"><div><span className="kicker">PEDIDO</span><h2>Finalizar pedido</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="panel-body"><label>Nome do cliente<input value={n} onChange={e=>setN(e.target.value)} placeholder="Seu nome"/></label><label>Número de telefone<input value={p} onChange={e=>setP(e.target.value)} placeholder="Seu número"/></label><label>Observações<textarea rows={3} value={o} onChange={e=>setO(e.target.value)} placeholder="Alguma informação adicional?"/></label><div className="summary"><b>Resumo dos produtos</b>{items.map(i=><div key={i.product.id}><span>{i.product.name} × {i.quantity}</span><strong>{money(i.subtotal)}</strong></div>)}<hr/><div><b>Total do pedido</b><strong>{money(total)}</strong></div></div><p className="note">O pedido será preparado para envio pelo contacto configurado no site.</p></div><div className="panel-foot"><button className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" disabled={!n.trim()||!p.trim()} onClick={()=>onSend(n,p,o)}>Enviar pedido <ArrowRight/></button></div></aside></>}

async function uploadImage(dataUrl:string,folder:string){const response=await fetch(dataUrl);const blob=await response.blob();const path=folder+"/"+crypto.randomUUID()+".jpg";const {error}=await supabase.storage.from(IMAGE_BUCKET).upload(path,blob,{contentType:"image/jpeg",cacheControl:"31536000",upsert:false});if(error)throw error;return supabase.storage.from(IMAGE_BUCKET).getPublicUrl(path).data.publicUrl}
function AdminPanel({isAdmin,onClose,onLogin}:{isAdmin:boolean;onClose:()=>void;onLogin:(ok:boolean)=>void}){const[email,setEmail]=useState(ADMIN_EMAIL),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const login=async()=>{setBusy(true);setError("");const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error||data.user?.email?.toLowerCase()!==ADMIN_EMAIL){await supabase.auth.signOut({scope:"local"});setError("Email ou palavra-passe inválidos, ou esta conta não tem acesso administrativo.");setBusy(false);return}setBusy(false);onLogin(true)};return <><div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}/><aside className="panel"><div className="panel-head"><div><span className="kicker">PARROT</span><h2>Área administrativa</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div>{isAdmin?<div className="panel-body admin-body"><div className="admin-welcome"><Sparkles/><h3>Acesso autorizado</h3><p>Está autenticado como <b>{ADMIN_EMAIL}</b>.</p><p>Os botões de edição, produtos, serviços e imagens estão agora disponíveis no site.</p></div><button className="btn primary" onClick={async()=>{await supabase.auth.signOut({scope:"local"});onLogin(false)}}>Terminar sessão</button></div>:<><div className="panel-body"><label>Email administrativo<input value={email} readOnly/></label><label>Palavra-passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void login()}} placeholder="A sua palavra-passe"/></label>{error&&<p className="admin-error">{error}</p>}<p className="note">Apenas a conta {ADMIN_EMAIL} pode administrar o catálogo. A palavra-passe não fica guardada no código.</p></div><div className="panel-foot"><button className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" disabled={busy||!password} onClick={()=>void login()}>{busy?"A entrar...":"Entrar no painel"}</button></div></>}</aside></>}
