create extension if not exists pgcrypto;

create table if not exists public.products (id text primary key,name text not null,category text not null check (category in ('Papelaria', 'Informática')),description text not null default '',price numeric(12,2) not null default 0,code text not null default '',stock integer not null default 0 check (stock >= 0),available boolean not null default true,image text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.services (type text primary key,title text not null,description text not null default '',image text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.products enable row level security;
alter table public.services enable row level security;
drop policy if exists "Public can read products" on public.products;
create policy "Public can read products" on public.products for select using (true);
drop policy if exists "Admin can insert products" on public.products;
create policy "Admin can insert products" on public.products for insert to authenticated with check ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com');
drop policy if exists "Admin can update products" on public.products;
create policy "Admin can update products" on public.products for update to authenticated using ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com') with check ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com');
drop policy if exists "Admin can delete products" on public.products;
create policy "Admin can delete products" on public.products for delete to authenticated using ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com');
drop policy if exists "Public can read services" on public.services;
create policy "Public can read services" on public.services for select using (true);
drop policy if exists "Admin can insert services" on public.services;
create policy "Admin can insert services" on public.services for insert to authenticated with check ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com');
drop policy if exists "Admin can update services" on public.services;
create policy "Admin can update services" on public.services for update to authenticated using ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com') with check ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com');
drop policy if exists "Admin can delete services" on public.services;
create policy "Admin can delete services" on public.services for delete to authenticated using ((auth.jwt() ->> 'email') = 'info.parrotdesign@gmail.com');
insert into public.services (type,title,description) values ('logo','Criação de logótipos','Marcas memoráveis e profissionais.'),('identity','Identidade visual','Sistemas visuais consistentes para a sua marca.'),('card','Cartões de visita','Apresentação profissional para o seu negócio.'),('flyer','Flyers e cartazes','Comunicação clara, impactante e pronta para impressão.'),('invite','Convites','Peças personalizadas para eventos e celebrações.'),('social','Banners para redes sociais','Conteúdo visual alinhado à sua identidade.'),('menu','Menus','Menus elegantes e preparados para impressão.'),('promo','Material promocional','Peças gráficas para campanhas e produtos.'),('print','Impressão e personalização','Do design ao material físico.'),('creative','Soluções criativas','Projetos sob medida para empresas e eventos.') on conflict (type) do nothing;
insert into public.products (id,name,category,description,price,code,stock,available,image) values ('starter-a4','Resma A4 80g','Papelaria','Papel A4 para impressão e uso diário.',0,'PAP-A4-80',10,true,'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&h=675&q=80'),('starter-notebook','Caderno A5','Papelaria','Caderno compacto para anotações e organização.',0,'PAP-CAD-A5',10,true,'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=900&h=675&q=80'),('starter-keyboard','Teclado USB','Informática','Teclado para computador com ligação USB.',0,'INF-TEC-USB',5,true,'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&h=675&q=80'),('starter-mouse','Rato USB','Informática','Rato USB para uso em computador e escritório.',0,'INF-MOU-USB',5,true,'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&h=675&q=80'),('starter-laptop','Computador portátil','Informática','Computador portátil para trabalho, estudo e criação.',0,'INF-LAP-001',2,true,'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&h=675&q=80') on conflict (id) do nothing;
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('parrot-images','parrot-images',true,5242880,array['image/*']) on conflict (id) do update set public=true,file_size_limit=5242880,allowed_mime_types=array['image/*'];
drop policy if exists "Admin can upload Parrot images" on storage.objects;
create policy "Admin can upload Parrot images" on storage.objects for insert to authenticated with check (bucket_id='parrot-images' and (auth.jwt() ->> 'email')='info.parrotdesign@gmail.com');
drop policy if exists "Admin can read Parrot image metadata" on storage.objects;
create policy "Admin can read Parrot image metadata" on storage.objects for select to authenticated using (bucket_id='parrot-images' and (auth.jwt() ->> 'email')='info.parrotdesign@gmail.com');
drop policy if exists "Admin can update Parrot images" on storage.objects;
create policy "Admin can update Parrot images" on storage.objects for update to authenticated using (bucket_id='parrot-images' and (auth.jwt() ->> 'email')='info.parrotdesign@gmail.com') with check (bucket_id='parrot-images' and (auth.jwt() ->> 'email')='info.parrotdesign@gmail.com');
drop policy if exists "Admin can delete Parrot images" on storage.objects;
create policy "Admin can delete Parrot images" on storage.objects for delete to authenticated using (bucket_id='parrot-images' and (auth.jwt() ->> 'email')='info.parrotdesign@gmail.com');
